# Generated by Django 4.2.17 on 2025-05-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppost",
            name="media_group_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
