# Generated by Django 4.2.17 on 2025-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupbot", "0002_grouppost_media_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.BigIntegerField(unique=True)),
                ("can_reply_ai", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
