# Generated by Django 4.2.17 on 2025-05-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupbot", "0004_userbot"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbot",
            name="username",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
