# Generated by Django 4.2.17 on 2025-05-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groupbot", "0005_userbot_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupSettings",
        ),
    ]
