# Generated by Django 4.2.17 on 2025-06-02 12:55

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groupbot", "0008_grouppost_display_text_grouppost_embedding_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("search_term", models.TextField()),
                (
                    "viewed_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(), default=list, size=None
                    ),
                ),
                ("page", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
