# Generated by Django 4.2.17 on 2025-06-02 12:57

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("groupbot", "0009_searchsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchsession",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=512,
                help_text="Vector embeddings (clip-vit-large-patch14) of the search term",
                null=True,
            ),
        ),
    ]
