# Generated by Django 4.2.17 on 2025-06-02 14:10

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("groupbot", "0010_searchsession_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppost",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                help_text="Vector embeddings (clip-vit-large-patch14) of the file content",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="searchsession",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                help_text="Vector embeddings (clip-vit-large-patch14) of the search term",
                null=True,
            ),
        ),
    ]
